### ISSUE TITLE
How to use the code?

### ISSUE THREAD

**Issue by mariolew** [ESanchezLozano/iCCR#1]
Hi, I want to know how to use the code, it's really hard to understand....

**Comment by ESanchezLozano** [comment]
Hi, sorry for the late reply,

Usage is as follows: 

Load the model, which will also load the parameters.

Then use track( model, video, params ); 

Model and params will be loaded from the .mat file, and video can be the path to where the video is stored, or [] for a webcam stream.

Hope this helps!

**Comment by mariolew** [comment]
Thanks.
