### ISSUE TITLE
Referenced model does not have SVM

### ISSUE THREAD

**Issue by mvalstar** [ESanchezLozano/iCCR#3]
After downloading the model referred to in the README and running track(model, video, params), I get:
```
Reference to non-existent field 'SVM'.

Error in track_with_box (line 33)
    params.lost_model.SVM = model.SVM;
```

**Comment by ESanchezLozano** [comment]
Are you loading the model with the parameters? Once the model is loaded, you should see in your workspace "model" and "params". Then call track(model,video,params);

It is specified this way in the README
