### ISSUE TITLE
dlib face detect doesn't work

### ISSUE THREAD

**Issue by mvalstar** [ESanchezLozano/iCCR#4]
On a Macbook, running Matlab R2017a, I get the following error when running track(model, video, params)

```
Undefined function or variable 'dlib_facedetect'.

Error in detect_pts_SDM

Error in track (line 85)
        pts = detect_pts_SDM( im , model );
```

**Comment by ESanchezLozano** [comment]
dlib is only compiled for Windows. I have updated the detect_pts_SDM function to use the built-in Viola-Jones face detector when no dlib is available.
