### ISSUE TITLE
cannot d/l model

### ISSUE THREAD

**Issue by Chris-W-Davis** [ESanchezLozano/iCCR#6]
When trying to download the model mat file from the sharepoint site I get {"error":{"code":"notSupported","message":"File is too big to download. Requested File Size: 628 MB, Max File Size Limit: 25 MB","innererror":{"code":"FileTooLarge"}}}

**Comment by ESanchezLozano** [comment]
Hi, sorry for the late reply. I have uploaded the code also to dropbox, you should be able to download it now from https://www.dropbox.com/s/6qwl2ca0m607o8d/model.rar?dl=0

Please let me know if you still have any issues regarding the model.

Thanks!

**Comment by Chris-W-Davis** [comment]
Thanks!
